/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doublechaine;

/**
 *
 * @author p1502716
 */
public class doublechaine extends javax.swing.JFrame {

    /**
     * Creates new form doublechaine
     */
    public doublechaine() {
        initComponents();
        listeChainee = new java.util.LinkedList<>();   // Initialisation de la Liste chainée
        
    }
    
    // Fonction qui vérifie si l'utilisateur a bien entré quelque chose
    // Renvoie false si la chaine = "" ou "   ")
     private boolean lireEtValider(String element)
    {
        if(element.equals("") || element.trim().equals("")) {
            javax.swing.JOptionPane.showMessageDialog(
                  this,
                  "Veuiller entrer quelque chose",
                  "Résultat",
                  javax.swing.JOptionPane.PLAIN_MESSAGE);
            return false;
        }
        else return true;
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelValeur = new javax.swing.JLabel();
        listText = new javax.swing.JTextField();
        labelListechainee = new javax.swing.JLabel();
        userValue = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion d'une double chaine");

        labelValeur.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelValeur.setText("Valeur:");

        labelListechainee.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelListechainee.setText("Liste Chainée:");

        jButton1.setText("Insérer au début");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insererDebut(evt);
            }
        });

        jButton2.setText("Insérer en Fin");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insererFin(evt);
            }
        });

        jButton3.setText("Retirer au début");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retirerDebut(evt);
            }
        });

        jButton4.setText("Retirer en fin");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retirerFin(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelValeur)
                .addGap(18, 18, 18)
                .addComponent(userValue, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(321, 321, 321))
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(30, 30, 30)
                        .addComponent(jButton2)
                        .addGap(120, 120, 120)
                        .addComponent(jButton3)
                        .addGap(27, 27, 27)
                        .addComponent(jButton4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelListechainee)
                        .addGap(18, 18, 18)
                        .addComponent(listText, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelValeur)
                    .addComponent(userValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelListechainee)
                    .addComponent(listText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insererDebut(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insererDebut
        text = userValue.getText().toString();
        if(lireEtValider(text)){
            listeChainee.addFirst(text);
        }
        listText.setText(listeChainee.toString());
    }//GEN-LAST:event_insererDebut

    private void insererFin(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insererFin
        text = userValue.getText().toString();
        if(lireEtValider(text)){
            listeChainee.addLast(text);
        }
        listText.setText(listeChainee.toString());
    }//GEN-LAST:event_insererFin

    private void retirerFin(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retirerFin
        listeChainee.removeLast();
        listText.setText(listeChainee.toString());
    }//GEN-LAST:event_retirerFin

    private void retirerDebut(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retirerDebut
        listeChainee.removeFirst();
        listText.setText(listeChainee.toString());
    }//GEN-LAST:event_retirerDebut

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(doublechaine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(doublechaine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(doublechaine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(doublechaine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new doublechaine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel labelListechainee;
    private javax.swing.JLabel labelValeur;
    private javax.swing.JTextField listText;
    private javax.swing.JTextField userValue;
    // End of variables declaration//GEN-END:variables
    private java.util.LinkedList<String> listeChainee;  // Déclaration de la Liste Chainee
    private String text; // Déclaration du text dans lequel nous allons mettre la valeur entrée par l'utilisateur
}
