/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestion_d_ensemble;

/**
 *
 * @author p1502716
 */
public class GestionEnsemble extends javax.swing.JFrame {

    /**
     * Creates new form GestionEnsemble
     */
    public GestionEnsemble() {
        initComponents();
        A = new java.util.TreeSet<>();
        B = new java.util.TreeSet<>();
        C = new java.util.TreeSet<>();
        D = new java.util.TreeSet<>();
        textValA.selectAll();
        textValA.requestFocus();
        setLocation(110,150);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelA = new javax.swing.JLabel();
        labelB = new javax.swing.JLabel();
        labelAUB = new javax.swing.JLabel();
        labelAnB = new javax.swing.JLabel();
        champA = new javax.swing.JTextField();
        champB = new javax.swing.JTextField();
        champAUB = new javax.swing.JTextField();
        champAnB = new javax.swing.JTextField();
        textValA = new javax.swing.JTextField();
        textValB = new javax.swing.JTextField();
        insererA = new javax.swing.JButton();
        insererB = new javax.swing.JButton();
        supprimerA = new javax.swing.JButton();
        supprimerB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GESTION D'ENSEMBLES");

        labelA.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelA.setText("A");

        labelB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelB.setText("B");

        labelAUB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelAUB.setText("AUB");

        labelAnB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelAnB.setText("AnB");

        champA.setEnabled(false);

        champB.setEnabled(false);

        champAUB.setEnabled(false);

        champAnB.setEnabled(false);

        insererA.setText("Insérer");
        insererA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insererA(evt);
            }
        });

        insererB.setText("Insérer");
        insererB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insererB(evt);
            }
        });

        supprimerA.setText("Supprimer");
        supprimerA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimer(evt);
            }
        });

        supprimerB.setText("Supprimer");
        supprimerB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimer(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelAUB, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAnB, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(labelB, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(labelA)))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(champA, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(champB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textValB, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textValA, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(insererA)
                            .addComponent(insererB))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(supprimerB)
                            .addComponent(supprimerA)))
                    .addComponent(champAUB)
                    .addComponent(champAnB))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelA)
                    .addComponent(champA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textValA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insererA)
                    .addComponent(supprimerA))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelB)
                    .addComponent(champB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textValB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insererB)
                    .addComponent(supprimerB))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAUB)
                    .addComponent(champAUB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAnB)
                    .addComponent(champAnB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(157, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insererA(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insererA
        lireEtValider(textValA);
    }//GEN-LAST:event_insererA

    private void insererB(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insererB
        // TODO add your handling code here:
    }//GEN-LAST:event_insererB

    private void supprimer(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimer
        // TODO add your handling code here:
    }//GEN-LAST:event_supprimer
    
    private boolean lireEtValider(javax.swing.JTextField element)
    {
     boolean ok = true;
     try {
        int number = Integer.parseInt(element.getText());
     }catch ( NumberFormatException e ) {
        javax.swing.JOptionPane.showMessageDialog(
               this,
               "Vous êtes mauvais",
               "Résultat",
               javax.swing.JOptionPane.PLAIN_MESSAGE); 
     }
     return ok;
   }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionEnsemble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionEnsemble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionEnsemble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionEnsemble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionEnsemble().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField champA;
    private javax.swing.JTextField champAUB;
    private javax.swing.JTextField champAnB;
    private javax.swing.JTextField champB;
    private javax.swing.JButton insererA;
    private javax.swing.JButton insererB;
    private javax.swing.JLabel labelA;
    private javax.swing.JLabel labelAUB;
    private javax.swing.JLabel labelAnB;
    private javax.swing.JLabel labelB;
    private javax.swing.JButton supprimerA;
    private javax.swing.JButton supprimerB;
    private javax.swing.JTextField textValA;
    private javax.swing.JTextField textValB;
    // End of variables declaration//GEN-END:variables
    java.util.SortedSet<Integer> A;
    java.util.SortedSet<Integer> B;
    java.util.SortedSet<Integer> C;
    java.util.SortedSet<Integer> D;
    private int valainsererA;
    private int valasupprimerA;
    private int valainsererB;
    private int valasupprimerB;
    
}
