/*
 * SelectFich.java
 *
 * Created on 23 avril 2007, 11:26
 */

package selectfich;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import static java.lang.Math.pow;
import java.util.ArrayList;


/**
 *
 * @author  Moonesh.Ramburrun
 */
public class SelectFich extends javax.swing.JFrame {
    
    /** Creates new form SelectFich */
    public SelectFich() {
        initComponents();
        listModel = new javax.swing.DefaultListModel<>( ); 
        jList1.setModel(listModel); 
// on fera jList1.setListData(listModel.toArray()); directement pour un obj de type ArrayList
        setLocation(200,150);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectionnerFichier = new javax.swing.JButton();
        editerFichier = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        calculer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("                                S E L E C T I O N     D ' U N    F I C H I E R    T E X T E  ");

        selectionnerFichier.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        selectionnerFichier.setText("Sélectionner un fichier texte");
        selectionnerFichier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectionnerFichierActionPerformed(evt);
            }
        });

        editerFichier.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        editerFichier.setText("Editer Le Fichier Des Notes");
        editerFichier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editerFichierActionPerformed(evt);
            }
        });

        jList1.setBackground(new java.awt.Color(102, 204, 255));
        jList1.setFont(new java.awt.Font("Monospaced", 1, 11)); // NOI18N
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.setFocusable(false);
        jScrollPane1.setViewportView(jList1);

        calculer.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        calculer.setText("Calculer");
        calculer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculerActionPerformed(evt);
                calculeMoyenne(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(selectionnerFichier)
                    .add(editerFichier, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 189, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(calculer, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 189, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(81, 81, 81)
                        .add(selectionnerFichier)
                        .add(43, 43, 43)
                        .add(editerFichier)
                        .add(41, 41, 41)
                        .add(calculer))
                    .add(layout.createSequentialGroup()
                        .add(50, 50, 50)
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 240, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectionnerFichierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectionnerFichierActionPerformed
     javax.swing.JFileChooser bdd;
     bdd = new javax.swing.JFileChooser( new java.io.File(".") );
     Filtre f;
     f = new Filtre();
     bdd.addChoosableFileFilter(f); // filtre à appliquer
     bdd.setFileFilter(f);
     if( bdd.showOpenDialog(null) == javax.swing.JFileChooser.APPROVE_OPTION ){
      // bdd.showSaveDialog pour la boîte de dialogue de sauvegarde
      fichier = bdd.getSelectedFile();
     } 
     if ( fichier == null ){ 
      javax.swing.JOptionPane.showMessageDialog(
              this,
              "Vous n'avez pas selectionné un nom de fichier : \"noms.txt\" choisi par défaut )" );
     }
     else{
      fichierSelectionne =  fichier.getName();
     } // fichier.getAbsolutePath();  pour nom absolu                
    }//GEN-LAST:event_selectionnerFichierActionPerformed

    private void editerFichierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editerFichierActionPerformed
     if ( fichier == null ){ 
      //javax.swing.JOptionPane.showMessageDialog( this, "Vous n'avez pas selectionné un nom de fichier : \"noms.txt\" choisi par défaut )" );
       fichier = new java.io.File(fichierSelectionne);
     }
     else {
     try {
       java.awt.Desktop.getDesktop().edit(fichier);
     }catch ( java.io.IOException e ) { 
       javax.swing.JOptionPane.showMessageDialog( this, e.getMessage() );
      } 
     }
    }//GEN-LAST:event_editerFichierActionPerformed

    private void calculerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculerActionPerformed
      // pour effacer le contenu de la liste listModel : listModel.clear();
      /*double d = 12.5;
      listModel.addElement( "Le fichier selectionné ou par défaut :");
      listModel.addElement("\"" + fichierSelectionne + "\"" );
      listModel.addElement(" ");
      listModel.addElement( "12.5 formatté avec String.format(\"%5.2f\",12.5) donne " +
         String.format("%5.2f",d) );*/
    }//GEN-LAST:event_calculerActionPerformed

    private void calculeMoyenne(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculeMoyenne

        File fe;
        fe = new File(fichierSelectionne);
        listModel.clear();
        
        BufferedReader fent;
        try {
            fent = new BufferedReader(new FileReader(fe));
            System.out.println("Voici le contenu du fich:");
            String enr;
            
            ArrayList<Etudiant> listeEtudiants = new ArrayList<Etudiant>();
            double totalDS1 = 0;
            double totalDS2 = 0;
            double totalEtudiants = 0;
            double moyenneDS1 = 0;
            double moyenneDS2 = 0;
            double moyenneEtudiants = 0;
            double ecartTypeDS1 = 0;
            double ecartTypeDS2 = 0;
            double totalnote1carre = 0;
            double totalnote2carre = 0;
            
            int nbEtudiant;
            
            while((enr=fent.readLine())!=null){
                String nomEtudiant = enr.substring(0,20);
                ArrayList<Double> notesEtudiant = new ArrayList<Double>();
                notesEtudiant.add(Double.parseDouble(enr.substring(20,25)));
                notesEtudiant.add(Double.parseDouble(enr.substring(26,31)));
                Etudiant etudiant = new Etudiant(nomEtudiant, notesEtudiant);
                listeEtudiants.add(etudiant);
                listModel.addElement(enr);
            }
            
            
            for(Etudiant etudiant : listeEtudiants){
               listModel.addElement(etudiant.toString());
               totalDS1 += etudiant.getNote1();
               totalDS2 += etudiant.getNote2();
               totalEtudiants += etudiant.moyenne();
               totalnote1carre += pow(etudiant.getNote1(),2);
               totalnote2carre += pow(etudiant.getNote2(),2);
            }
            nbEtudiant = listeEtudiants.size();
            moyenneDS1 = totalDS1/nbEtudiant;
            moyenneDS2 = totalDS2/nbEtudiant;
            moyenneEtudiants = totalEtudiants/nbEtudiant;
            ecartTypeDS1 = Math.sqrt((totalnote1carre/nbEtudiant) - pow(moyenneDS1,2));
            ecartTypeDS2 = Math.sqrt((totalnote2carre/nbEtudiant) - pow(moyenneDS2,2));
            
            listModel.addElement("---------------------------");
            listModel.addElement("Moyenne" + " pour " + nbEtudiant + " etudiants : " + String.format("%.2f",moyenneDS1) + "           " + String.format("%.2f",moyenneDS2) + "      " + String.format("%.2f",moyenneEtudiants));
            listModel.addElement("Ec.Type" + " pour " + nbEtudiant + " etudiants : " + String.format("%.2f", ecartTypeDS1) + "   " + String.format("%.2f", ecartTypeDS2));
            
            
        } catch ( java.io.IOException e ) { 
       javax.swing.JOptionPane.showMessageDialog( this, e.getMessage() );
      } 
    }//GEN-LAST:event_calculeMoyenne
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
               new SelectFich().setVisible(true);
        }
     });
   }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculer;
    private javax.swing.JButton editerFichier;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton selectionnerFichier;
    // End of variables declaration//GEN-END:variables
    private javax.swing.DefaultListModel<String> listModel; 
    private String fichierSelectionne = "noms.txt";
    private java.io.File fichier = null;        

}
